### ISSUE TITLE
Add a process exit timer for inactive PlumaDriver instances

### ISSUE THREAD

**Issue by poftadeh** [Seneca-CDOT/plumadriver#108]
**What would you like to be added**:
Add a timer (duration can be set as an option when creating a session) that will quit the driver after a specified period without activity.

**Why is this needed**:
Inactive instances are not particularly useful and may possibly interfere with other tests.

**Comment by pynnl** [comment]
@poftadeh Is it supposed to quit the driver or just clear the inactive instances (sessions)?

**Comment by poftadeh** [comment]
@pynnl I've been a bit busy this week, so unable to check recent PRs or issues unfortunately. I'll take a look tomorrow and let you know.
