### ISSUE TITLE
Make issue template

### ISSUE THREAD

**Issue by miggs125** [Seneca-CDOT/plumadriver#16]
We need a template to log issues, simplify debugging and make the code base more maintainable. This should at the very least include the following:
- reproduction environment: OS, code that caused the issue/bug
- expected value vs actual value

any other ideas as to what to include in the template?

**Comment by manekenpix** [comment]
Possible template

#### Description
Example: My flux capacitor doesn't work when I try to travel to the future

#### Steps/Code to Reproduce
Example:
```
import something here
import anotherThing here
```
If the code is too long, feel free to put it in a public gist and link
it in the issue: https://gist.github.com

When possible use plumadriver testing examples to reproduce the errors. (do we have testing examples?)

#### Expected Results
Please paste or describe the expected results.
Example: I go to the future and get to see what happens to me

#### Actual Results
Please paste or specifically describe the actual output or traceback.
Example: ```'Flux Capacitor out of gas'```

#### Versions
Please run the following snippet and paste the output below.
```Snippets to get platform, system, plumadriver version, etc```

Thanks for contributing!

**Comment by miggs125** [comment]
@manekenpix  looks good! Does anyone else want to weigh in on this? @poftadeh @ctyler

**Comment by poftadeh** [comment]
Looks good. We could also refer to Kubernetes' templates: 

https://github.com/kubernetes/kubernetes/issues/new/choose
