### ISSUE TITLE
getText returns innerHTML instead of textContent

### ISSUE THREAD

**Issue by adamjordannexj** [Seneca-CDOT/plumadriver#17]
Description
PlumaDriver .getText() returns the innerHTML of the element instead of the textContent.

Steps/Code to Reproduce
   
   public static void test(WebDriver driver)
   {
      driver.get("http://captive.apple.com");
      WebElement element = driver.findElement(By.tagName("head"));
      Assert.assertTrue(element.getText().equals("Success"));
   }

Expected Results
Passing in a ChromeDriver instance and a PlumaDriver instance should both pass.

Actual Results
Passing in a ChromeDriver instance passes. Passing in a PlumaDriver instance fails, and the result of the call is <title>Success</title> instead of simply Success.

Versions
Is PlumaDriver versioned yet?

**Comment by miggs125** [comment]
fixed, changes made to master. Let us know if there are any additional issues relating to getText()
