### ISSUE TITLE
Unable to navigate to a file on the local filesystem

### ISSUE THREAD

**Issue by adamjordannexj** [Seneca-CDOT/plumadriver#18]
Description
.get fails to navigate to a path on the local filesystem. The use case for this is twofold; one, it would be nice to test small items quickly without standing up a web server, and we also have a large offline demo app which displays examples of each of our control types. The test .html page is very basic but I'll attach it anyways. (as .txt since I can't upload an .html)
[test.txt](https://github.com/Seneca-CDOT/plumadriver/files/3262934/test.txt)

Steps/Code to Reproduce
   public static void test(WebDriver driver)
   {
     driver.get("file://C:/work/test.html");
   }

Expected Results
Both ChromeDriver and the PlumaDriver should navigate properly.

Actual Results
ChromeDriver navigates properly. PlumaDriver fails on the get. Stack trace as follows:
[stack.txt](https://github.com/Seneca-CDOT/plumadriver/files/3262921/stack.txt)

Error log: 
[pluma_error_log.txt](https://github.com/Seneca-CDOT/plumadriver/files/3262930/pluma_error_log.txt)

Versions
latest

**Comment by miggs125** [comment]
fixed, changes made to master. Let us know if there are any additional issues relating to this. Additionally, findElement by xpath is now functional
