### ISSUE TITLE
executeScript: incorrect return value of undefined

### ISSUE THREAD

**Issue by adamjordannexj** [Seneca-CDOT/plumadriver#20]
Description
executeScript returns an empty map instead of null when executing 'return undefined;' or 'return;'

Steps/Code to Reproduce
public static void test(WebDriver driver)
   {
      driver.get("http://captive.apple.com");

      Assert.assertEquals(null, ((JavascriptExecutor)driver).executeScript("return null;"));      
      Assert.assertEquals(null, ((JavascriptExecutor)driver).executeScript("return undefined;"));
      Assert.assertEquals(null, ((JavascriptExecutor)driver).executeScript("return;"));     
   }

Expected Results
All three asserts should pass in both Chrome and Pluma, since, according to the Selenium Javadoc, "Unless the value is null _or there is no return value_, in which null is returned"

https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/JavascriptExecutor.html

Actual Results
All three pass in Chrome. The first passes in Pluma, and the next two fail.
Exception in thread "main" junit.framework.AssertionFailedError: expected:<null> but was:<{}>
	at junit.framework.Assert.fail(Assert.java:47)

Versions
Against this build: https://github.com/Seneca-CDOT/plumadriver/commit/21e5022b1f18f85c3c9bf6c5b2659ca6ff15a19e

**Comment by poftadeh** [comment]
- [x] Add `JavaScriptError` and `ScriptTimeoutError` classes
- [ ] fix bug related to missing `window` and `document` objects in execute script context.
