### ISSUE TITLE
Add airbnb linter rules

### ISSUE THREAD

**Issue by poftadeh** [Seneca-CDOT/plumadriver#208]
**What would you like to be changed**:
Add `airbnb-base` to the eslint config.

**Why is this needed**:
It catches several existing errors that should accelerate future code review:

![image](https://user-images.githubusercontent.com/30670414/95546636-20e9b700-09cf-11eb-8c63-a1a3e46499a1.png)

I've done initial config work in the branch `feat/add-airbnb-rules`, so all that is needed is to fix the linter errors it's catching. This is low priority, so I'd be willing to do it if the team is busy with other work.

**Comment by pynnl** [comment]
I can work on this if you don't mind. @zthaver , @MeisterRed If you want to give a try just let me know.

**Comment by poftadeh** [comment]
```
'no-console': [
      'error',
      {
        allow: ['warn', 'error', 'info'],
      },
    ],
```

For console errors, this rule can be added. It'll catch leftover console.logs used for debugging, but allow console.info/warn/error in production.

**Comment by pynnl** [comment]
The spec doesn't allow [mutating params](https://github.com/airbnb/javascript#functions--mutate-params) which we **do want to** use in some places (such as `BrowserConfig.injectAPIs`). There are two solutions for this, disabling every affected lines, or creating a pattern for the arguments we want to mutate (for example `^_`). @poftadeh What do you think?

**Comment by poftadeh** [comment]
I'm okay with setting `"no-param-reassign": ["error", { "props": false }]` to avoid having to constantly fight with the linter on this.
