### ISSUE TITLE
executeScript: issues returning WebElements

### ISSUE THREAD

**Issue by adamjordannexj** [Seneca-CDOT/plumadriver#22]
Description
Exceptions when attempting to return a WebElement as a result of executeScript. The first test should just pass an element in and retrieve that same element. The second test should try to retrieve that same element directly.

Steps/Code to Reproduce
public static void test(WebDriver driver)
   {
      driver.get("http://captive.apple.com");
      WebElement element = driver.findElement(By.tagName("body"));
      
      WebElement e1 = (WebElement)((JavascriptExecutor)driver).executeScript("return arguments[0];", element);
      Assert.assertEquals(e1, element);
            
      WebElement e2 = (WebElement)((JavascriptExecutor)driver).executeScript("return document.getElementsByTagName('body')[0];");
      Assert.assertEquals(e2, element);
   }

Expected Results
Both asserts should pass in Pluma, as they do in Chrome.

Actual Results
Chrome passes. The first test fails with an exception; an error log is generated, but completely empty.
Exception in thread "main" java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
	at nexj.core.testing.ui.application.Test.test(Test.java:99)
	at nexj.core.testing.ui.application.Test.main(Test.java:31)

The second test throws a very familiar console error, and 'document is not defined' is in the error log. 
[pluma_error_log_2.txt](https://github.com/Seneca-CDOT/plumadriver/files/3263486/pluma_error_log_2.txt)
[output_2.txt](https://github.com/Seneca-CDOT/plumadriver/files/3263487/output_2.txt)

Versions
Against this version: https://github.com/Seneca-CDOT/plumadriver/commit/21e5022b1f18f85c3c9bf6c5b2659ca6ff15a19e

**Comment by miggs125** [comment]
fixed. changes merged to master. returning WebElements should be possible now
