### ISSUE TITLE
Convert Project Code to Typescript

### ISSUE THREAD

**Issue by poftadeh** [Seneca-CDOT/plumadriver#8]
As discussed, static type-checking will be useful as the project grows in size.

**Comment by miggs125** [comment]
Work on this has begun on the typescript branch. Help is welcome.

**Comment by poftadeh** [comment]
Project does not compile under `strict` mode. To close this issue, resolving errors related `implicit any` and missing declarations need to be addressed.

**Comment by poftadeh** [comment]
Initial groundwork for this has been completed. Strict mode changes remains to be done--see #32.
