### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by poftadeh** [Seneca-CDOT/plumadriver#99]
**What would you like to be added**:
Improve automation in the repo by adding CI. 

**Why is this needed**:
It will be helpful when handling pull requests.

**Additional context**
GitHub `Actions` cannot be enabled on this repo, so it is worth considering using a service such as  `CricleCI` instead.

**Comment by humphd** [comment]
I was just about to file an issue for this, glad to see you have it already.  I'll see if I can interest one of my students to add it, since we've done a bunch of this already in other projects.

**Comment by c3ho** [comment]
Hi, if this is not taken, I'd like to try taking on this issue.

**Comment by poftadeh** [comment]
@c3ho sounds good to me.

**Comment by manekenpix** [comment]
I'd like to help with this one.

**Comment by manekenpix** [comment]
Closed via #137
